// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrAgRX8qen42ScEg52VFaRoNtJWYF6-7M',
    appId: '1:295453268895:web:ebeec4acd4f72e623ffbaa',
    messagingSenderId: '295453268895',
    projectId: 'my-e-commercial-app-423aa',
    authDomain: 'my-e-commercial-app-423aa.firebaseapp.com',
    storageBucket: 'my-e-commercial-app-423aa.appspot.com',
    measurementId: 'G-JJ9HNG4TQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYu5m8M__n8I4dVHIdF5ua9Fr6frDB5zM',
    appId: '1:295453268895:android:2ef8bda59baeb73d3ffbaa',
    messagingSenderId: '295453268895',
    projectId: 'my-e-commercial-app-423aa',
    storageBucket: 'my-e-commercial-app-423aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpcgaMRXgFeKMjFMc3h0xN2jJoZnf0n7s',
    appId: '1:295453268895:ios:15abc86a4181900d3ffbaa',
    messagingSenderId: '295453268895',
    projectId: 'my-e-commercial-app-423aa',
    storageBucket: 'my-e-commercial-app-423aa.appspot.com',
    iosClientId: '295453268895-8h65fd9fphg3nq5hq5p6suqj2uantjig.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpcgaMRXgFeKMjFMc3h0xN2jJoZnf0n7s',
    appId: '1:295453268895:ios:15abc86a4181900d3ffbaa',
    messagingSenderId: '295453268895',
    projectId: 'my-e-commercial-app-423aa',
    storageBucket: 'my-e-commercial-app-423aa.appspot.com',
    iosClientId: '295453268895-8h65fd9fphg3nq5hq5p6suqj2uantjig.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullapp',
  );
}
